version: 2
updates:
  - package-ecosystem: pip
    directory: "/flask-gunicorn"
    schedule:
      interval: daily
      time: "00:00"
    open-pull-requests-limit: 5
    allow:
      - dependency-type: direct
    rebase-strategy: disabled
  - package-ecosystem: pip
    directory: "/fastapi-gunicorn"
    schedule:
      interval: daily
      time: "00:00"
    open-pull-requests-limit: 5
    allow:
      - dependency-type: direct
    rebase-strategy: disabled
  - package-ecosystem: pip
    directory: "/tests"
    schedule:
      interval: daily
      time: "00:00"
    open-pull-requests-limit: 5
    allow:
      - dependency-type: direct
    rebase-strategy: disabled
  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: daily
      time: "00:00"
    open-pull-requests-limit: 5
    allow:
      - dependency-type: direct
    rebase-strategy: disabled
