name: Build and test flask-gunicorn

on:
  push:
    # Matching semver tags: v3.8.2, etc.
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
  pull_request:
    types: [opened, ready_for_review, reopened, synchronize]
    paths:
      - flask-gunicorn/**
      - Dockerfile
      - serve.py
      - tests/**

jobs:
  e2e:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run tests
        env:
          APP: flask-gunicorn
          COMPOSE_DOCKER_CLI_BUILD: 1
          DOCKER_BUILDKIT: 1
        run: |
          docker-compose -f tests/docker-compose.yml up --build \
          --abort-on-container-exit \
          --always-recreate-deps
  release:
    runs-on: ubuntu-latest
    # Only push the image on new tag event
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Tag and push image
        uses: docker/build-push-action@v1.1.0
        env:
          DOCKER_BUILDKIT: 1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: basisai/flask-gunicorn
          build_args: APP=flask-gunicorn
          tags: flask-gunicorn
          tag_with_ref: true
